SAVE_DIR          : output
MODEL             : ClipCap
WEIGHTS           : ./checkpoints/clipcap/coco_weights.pt
DATASET           : coco
DATASET_ROOT      : './data/coco/'
TRAIN_DATA_PATH   : ./data/coco_kor/coco_train.pkl
VAL_DATA_PATH     : ./data/coco_kor/coco_test.pkl
SEQ_LENGTH        : 40
BATCH_SIZE        : 32
EPOCHS            : 100
EVAL_INTERVAL     : 10
LR                : 0.001
WEIGHT_DECAY      : 0.01
WARMUP            : 10